-- Auto-generated: Odds API → ESPN team name mapping
CREATE TABLE IF NOT EXISTS team_name_map (odds_api_name TEXT PRIMARY KEY, espn_name TEXT NOT NULL, sport TEXT NOT NULL);
TRUNCATE team_name_map;

INSERT INTO team_name_map VALUES ('Arizona Cardinals', 'Arizona Cardinals', 'nfl');
INSERT INTO team_name_map VALUES ('Atlanta Falcons', 'Atlanta Falcons', 'nfl');
INSERT INTO team_name_map VALUES ('Baltimore Ravens', 'Baltimore Ravens', 'nfl');
INSERT INTO team_name_map VALUES ('Buffalo Bills', 'Buffalo Bills', 'nfl');
INSERT INTO team_name_map VALUES ('Carolina Panthers', 'Carolina Panthers', 'nfl');
INSERT INTO team_name_map VALUES ('Chicago Bears', 'Chicago Bears', 'nfl');
INSERT INTO team_name_map VALUES ('Cincinnati Bengals', 'Cincinnati Bengals', 'nfl');
INSERT INTO team_name_map VALUES ('Cleveland Browns', 'Cleveland Browns', 'nfl');
INSERT INTO team_name_map VALUES ('Dallas Cowboys', 'Dallas Cowboys', 'nfl');
INSERT INTO team_name_map VALUES ('Denver Broncos', 'Denver Broncos', 'nfl');
INSERT INTO team_name_map VALUES ('Detroit Lions', 'Detroit Lions', 'nfl');
INSERT INTO team_name_map VALUES ('Green Bay Packers', 'Green Bay Packers', 'nfl');
INSERT INTO team_name_map VALUES ('Houston Texans', 'Houston Texans', 'nfl');
INSERT INTO team_name_map VALUES ('Indianapolis Colts', 'Indianapolis Colts', 'nfl');
INSERT INTO team_name_map VALUES ('Jacksonville Jaguars', 'Jacksonville Jaguars', 'nfl');
INSERT INTO team_name_map VALUES ('Kansas City Chiefs', 'Kansas City Chiefs', 'nfl');
INSERT INTO team_name_map VALUES ('Las Vegas Raiders', 'Las Vegas Raiders', 'nfl');
INSERT INTO team_name_map VALUES ('Los Angeles Chargers', 'Los Angeles Chargers', 'nfl');
INSERT INTO team_name_map VALUES ('Los Angeles Rams', 'Los Angeles Rams', 'nfl');
INSERT INTO team_name_map VALUES ('Miami Dolphins', 'Miami Dolphins', 'nfl');
INSERT INTO team_name_map VALUES ('Minnesota Vikings', 'Minnesota Vikings', 'nfl');
INSERT INTO team_name_map VALUES ('New England Patriots', 'New England Patriots', 'nfl');
INSERT INTO team_name_map VALUES ('New Orleans Saints', 'New Orleans Saints', 'nfl');
INSERT INTO team_name_map VALUES ('New York Giants', 'New York Giants', 'nfl');
INSERT INTO team_name_map VALUES ('New York Jets', 'New York Jets', 'nfl');
INSERT INTO team_name_map VALUES ('Philadelphia Eagles', 'Philadelphia Eagles', 'nfl');
INSERT INTO team_name_map VALUES ('Pittsburgh Steelers', 'Pittsburgh Steelers', 'nfl');
INSERT INTO team_name_map VALUES ('San Francisco 49ers', 'San Francisco 49ers', 'nfl');
INSERT INTO team_name_map VALUES ('Seattle Seahawks', 'Seattle Seahawks', 'nfl');
INSERT INTO team_name_map VALUES ('Tampa Bay Buccaneers', 'Tampa Bay Buccaneers', 'nfl');
INSERT INTO team_name_map VALUES ('Tennessee Titans', 'Tennessee Titans', 'nfl');
INSERT INTO team_name_map VALUES ('Washington Commanders', 'Washington Commanders', 'nfl');
INSERT INTO team_name_map VALUES ('Abilene Christian Wildcats', 'Abilene Christian Wildcats', 'cfb');
INSERT INTO team_name_map VALUES ('Air Force Falcons', 'Air Force Falcons', 'cfb');
INSERT INTO team_name_map VALUES ('Akron Zips', 'Akron Zips', 'cfb');
INSERT INTO team_name_map VALUES ('Alabama A&M Bulldogs', 'Alabama A&M Bulldogs', 'cfb');
INSERT INTO team_name_map VALUES ('Alabama Crimson Tide', 'Alabama Crimson Tide', 'cfb');
INSERT INTO team_name_map VALUES ('Arizona State Sun Devils', 'Arizona State Sun Devils', 'cfb');
INSERT INTO team_name_map VALUES ('Arizona Wildcats', 'Arizona Wildcats', 'cfb');
INSERT INTO team_name_map VALUES ('Arkansas Razorbacks', 'Arkansas Razorbacks', 'cfb');
INSERT INTO team_name_map VALUES ('Arkansas State Red Wolves', 'Arkansas State Red Wolves', 'cfb');
INSERT INTO team_name_map VALUES ('Army Black Knights', 'Army Black Knights', 'cfb');
INSERT INTO team_name_map VALUES ('Auburn Tigers', 'Auburn Tigers', 'cfb');
INSERT INTO team_name_map VALUES ('Austin Peay Governors', 'Austin Peay Governors', 'cfb');
INSERT INTO team_name_map VALUES ('BYU Cougars', 'BYU Cougars', 'cfb');
INSERT INTO team_name_map VALUES ('Ball State Cardinals', 'Ball State Cardinals', 'cfb');
INSERT INTO team_name_map VALUES ('Baylor Bears', 'Baylor Bears', 'cfb');
INSERT INTO team_name_map VALUES ('Bethune-Cookman Wildcats', 'Bethune-Cookman Wildcats', 'cfb');
INSERT INTO team_name_map VALUES ('Boise State Broncos', 'Boise State Broncos', 'cfb');
INSERT INTO team_name_map VALUES ('Boston College Eagles', 'Boston College Eagles', 'cfb');
INSERT INTO team_name_map VALUES ('Bowling Green Falcons', 'Bowling Green Falcons', 'cfb');
INSERT INTO team_name_map VALUES ('Bucknell Bison', 'Bucknell Bison', 'cfb');
INSERT INTO team_name_map VALUES ('Buffalo Bulls', 'Buffalo Bulls', 'cfb');
INSERT INTO team_name_map VALUES ('California Golden Bears', 'California Golden Bears', 'cfb');
INSERT INTO team_name_map VALUES ('Campbell Fighting Camels', 'Campbell Fighting Camels', 'cfb');
INSERT INTO team_name_map VALUES ('Central Arkansas Bears', 'Central Arkansas Bears', 'cfb');
INSERT INTO team_name_map VALUES ('Central Michigan Chippewas', 'Central Michigan Chippewas', 'cfb');
INSERT INTO team_name_map VALUES ('Charleston Southern Buccaneers', 'Charleston Southern Buccaneers', 'cfb');
INSERT INTO team_name_map VALUES ('Charlotte 49ers', 'Charlotte 49ers', 'cfb');
INSERT INTO team_name_map VALUES ('Chattanooga Mocs', 'Chattanooga Mocs', 'cfb');
INSERT INTO team_name_map VALUES ('Cincinnati Bearcats', 'Cincinnati Bearcats', 'cfb');
INSERT INTO team_name_map VALUES ('Citadel Bulldogs', 'The Citadel Bulldogs', 'cfb');
INSERT INTO team_name_map VALUES ('Clemson Tigers', 'Clemson Tigers', 'cfb');
INSERT INTO team_name_map VALUES ('Coastal Carolina Chanticleers', 'Coastal Carolina Chanticleers', 'cfb');
INSERT INTO team_name_map VALUES ('Colgate Raiders', 'Colgate Raiders', 'cfb');
INSERT INTO team_name_map VALUES ('Colorado Buffaloes', 'Colorado Buffaloes', 'cfb');
INSERT INTO team_name_map VALUES ('Colorado State Rams', 'Colorado State Rams', 'cfb');
INSERT INTO team_name_map VALUES ('Davidson Wildcats', 'Davidson Wildcats', 'cfb');
INSERT INTO team_name_map VALUES ('Duke Blue Devils', 'Duke Blue Devils', 'cfb');
INSERT INTO team_name_map VALUES ('East Carolina Pirates', 'East Carolina Pirates', 'cfb');
INSERT INTO team_name_map VALUES ('East Tennessee State Buccaneers', 'East Tennessee State Buccaneers', 'cfb');
INSERT INTO team_name_map VALUES ('Eastern Illinois Panthers', 'Eastern Illinois Panthers', 'cfb');
INSERT INTO team_name_map VALUES ('Eastern Kentucky Colonels', 'Eastern Kentucky Colonels', 'cfb');
INSERT INTO team_name_map VALUES ('Eastern Michigan Eagles', 'Eastern Michigan Eagles', 'cfb');
INSERT INTO team_name_map VALUES ('Florida Atlantic Owls', 'Florida Atlantic Owls', 'cfb');
INSERT INTO team_name_map VALUES ('Florida Gators', 'Florida Gators', 'cfb');
INSERT INTO team_name_map VALUES ('Florida International Panthers', 'Florida International Panthers', 'cfb');
INSERT INTO team_name_map VALUES ('Florida State Seminoles', 'Florida State Seminoles', 'cfb');
INSERT INTO team_name_map VALUES ('Fresno State Bulldogs', 'Fresno State Bulldogs', 'cfb');
INSERT INTO team_name_map VALUES ('Furman Paladins', 'Furman Paladins', 'cfb');
INSERT INTO team_name_map VALUES ('Gardner-Webb Runnin Bulldogs', 'Gardner-Webb Runnin'' Bulldogs', 'cfb');
INSERT INTO team_name_map VALUES ('Georgetown Hoyas', 'Georgetown Hoyas', 'cfb');
INSERT INTO team_name_map VALUES ('Georgia Bulldogs', 'Georgia Bulldogs', 'cfb');
INSERT INTO team_name_map VALUES ('Georgia Southern Eagles', 'Georgia Southern Eagles', 'cfb');
INSERT INTO team_name_map VALUES ('Georgia State Panthers', 'Georgia State Panthers', 'cfb');
INSERT INTO team_name_map VALUES ('Georgia Tech Yellow Jackets', 'Georgia Tech Yellow Jackets', 'cfb');
INSERT INTO team_name_map VALUES ('Grambling State Tigers', 'Grambling Tigers', 'cfb');
INSERT INTO team_name_map VALUES ('Hawaii Rainbow Warriors', 'Hawai''i Rainbow Warriors', 'cfb');
INSERT INTO team_name_map VALUES ('Holy Cross Crusaders', 'Holy Cross Crusaders', 'cfb');
INSERT INTO team_name_map VALUES ('Houston Baptist Huskies', 'Houston Cougars', 'cfb');
INSERT INTO team_name_map VALUES ('Houston Cougars', 'Houston Cougars', 'cfb');
INSERT INTO team_name_map VALUES ('Idaho State Bengals', 'Idaho State Bengals', 'cfb');
INSERT INTO team_name_map VALUES ('Idaho Vandals', 'Idaho Vandals', 'cfb');
INSERT INTO team_name_map VALUES ('Illinois Fighting Illini', 'Illinois Fighting Illini', 'cfb');
INSERT INTO team_name_map VALUES ('Illinois State Redbirds', 'Illinois State Redbirds', 'cfb');
INSERT INTO team_name_map VALUES ('Indiana Hoosiers', 'Indiana Hoosiers', 'cfb');
INSERT INTO team_name_map VALUES ('Indiana State Sycamores', 'Indiana State Sycamores', 'cfb');
INSERT INTO team_name_map VALUES ('Iowa Hawkeyes', 'Iowa Hawkeyes', 'cfb');
INSERT INTO team_name_map VALUES ('Iowa State Cyclones', 'Iowa State Cyclones', 'cfb');
INSERT INTO team_name_map VALUES ('Jacksonville State Gamecocks', 'Jacksonville State Gamecocks', 'cfb');
INSERT INTO team_name_map VALUES ('James Madison Dukes', 'James Madison Dukes', 'cfb');
INSERT INTO team_name_map VALUES ('Kansas Jayhawks', 'Kansas Jayhawks', 'cfb');
INSERT INTO team_name_map VALUES ('Kansas State Wildcats', 'Kansas State Wildcats', 'cfb');
INSERT INTO team_name_map VALUES ('Kennesaw State Owls', 'Kennesaw State Owls', 'cfb');
INSERT INTO team_name_map VALUES ('Kent State Golden Flashes', 'Kent State Golden Flashes', 'cfb');
INSERT INTO team_name_map VALUES ('Kentucky Wildcats', 'Kentucky Wildcats', 'cfb');
INSERT INTO team_name_map VALUES ('LSU Tigers', 'LSU Tigers', 'cfb');
INSERT INTO team_name_map VALUES ('Lamar Cardinals', 'Lamar Cardinals', 'cfb');
INSERT INTO team_name_map VALUES ('Liberty Flames', 'Liberty Flames', 'cfb');
INSERT INTO team_name_map VALUES ('Louisiana Ragin Cajuns', 'Louisiana Ragin'' Cajuns', 'cfb');
INSERT INTO team_name_map VALUES ('Louisiana Tech Bulldogs', 'Louisiana Tech Bulldogs', 'cfb');
INSERT INTO team_name_map VALUES ('Louisville Cardinals', 'Louisville Cardinals', 'cfb');
INSERT INTO team_name_map VALUES ('Marshall Thundering Herd', 'Marshall Thundering Herd', 'cfb');
INSERT INTO team_name_map VALUES ('Maryland Terrapins', 'Maryland Terrapins', 'cfb');
INSERT INTO team_name_map VALUES ('Memphis Tigers', 'Memphis Tigers', 'cfb');
INSERT INTO team_name_map VALUES ('Merrimack Warriors', 'Merrimack Warriors', 'cfb');
INSERT INTO team_name_map VALUES ('Miami (OH) RedHawks', 'Miami (OH) RedHawks', 'cfb');
INSERT INTO team_name_map VALUES ('Miami Hurricanes', 'Miami Hurricanes', 'cfb');
INSERT INTO team_name_map VALUES ('Michigan State Spartans', 'Michigan State Spartans', 'cfb');
INSERT INTO team_name_map VALUES ('Michigan Wolverines', 'Michigan Wolverines', 'cfb');
INSERT INTO team_name_map VALUES ('Middle Tennessee Blue Raiders', 'Middle Tennessee Blue Raiders', 'cfb');
INSERT INTO team_name_map VALUES ('Minnesota Golden Gophers', 'Minnesota Golden Gophers', 'cfb');
INSERT INTO team_name_map VALUES ('Mississippi State Bulldogs', 'Mississippi State Bulldogs', 'cfb');
INSERT INTO team_name_map VALUES ('Mississippi Valley State Delta Devils', 'Mississippi Valley State Delta Devils', 'cfb');
INSERT INTO team_name_map VALUES ('Missouri Tigers', 'Missouri Tigers', 'cfb');
INSERT INTO team_name_map VALUES ('Morgan State Bears', 'Morgan State Bears', 'cfb');
INSERT INTO team_name_map VALUES ('NC State Wolfpack', 'NC State Wolfpack', 'cfb');
INSERT INTO team_name_map VALUES ('Navy Midshipmen', 'Navy Midshipmen', 'cfb');
INSERT INTO team_name_map VALUES ('Nebraska Cornhuskers', 'Nebraska Cornhuskers', 'cfb');
INSERT INTO team_name_map VALUES ('Nevada Wolf Pack', 'Nevada Wolf Pack', 'cfb');
INSERT INTO team_name_map VALUES ('New Mexico Lobos', 'New Mexico Lobos', 'cfb');
INSERT INTO team_name_map VALUES ('New Mexico State Aggies', 'New Mexico State Aggies', 'cfb');
INSERT INTO team_name_map VALUES ('Nicholls State Colonels', 'Nicholls Colonels', 'cfb');
INSERT INTO team_name_map VALUES ('Norfolk State Spartans', 'Norfolk State Spartans', 'cfb');
INSERT INTO team_name_map VALUES ('North Alabama Lions', 'North Alabama Lions', 'cfb');
INSERT INTO team_name_map VALUES ('North Carolina Central Eagles', 'North Carolina Central Eagles', 'cfb');
INSERT INTO team_name_map VALUES ('North Carolina Tar Heels', 'North Carolina Tar Heels', 'cfb');
INSERT INTO team_name_map VALUES ('North Dakota Fighting Hawks', 'North Dakota Fighting Hawks', 'cfb');
INSERT INTO team_name_map VALUES ('North Texas Mean Green', 'North Texas Mean Green', 'cfb');
INSERT INTO team_name_map VALUES ('Northern Illinois Huskies', 'Northern Illinois Huskies', 'cfb');
INSERT INTO team_name_map VALUES ('Northern Iowa Panthers', 'Northern Iowa Panthers', 'cfb');
INSERT INTO team_name_map VALUES ('Northwestern Wildcats', 'Northwestern Wildcats', 'cfb');
INSERT INTO team_name_map VALUES ('Notre Dame Fighting Irish', 'Notre Dame Fighting Irish', 'cfb');
INSERT INTO team_name_map VALUES ('Ohio Bobcats', 'Ohio Bobcats', 'cfb');
INSERT INTO team_name_map VALUES ('Ohio State Buckeyes', 'Ohio State Buckeyes', 'cfb');
INSERT INTO team_name_map VALUES ('Oklahoma Sooners', 'Oklahoma Sooners', 'cfb');
INSERT INTO team_name_map VALUES ('Oklahoma State Cowboys', 'Oklahoma State Cowboys', 'cfb');
INSERT INTO team_name_map VALUES ('Old Dominion Monarchs', 'Old Dominion Monarchs', 'cfb');
INSERT INTO team_name_map VALUES ('Ole Miss Rebels', 'Ole Miss Rebels', 'cfb');
INSERT INTO team_name_map VALUES ('Oregon Ducks', 'Oregon Ducks', 'cfb');
INSERT INTO team_name_map VALUES ('Oregon State Beavers', 'Oregon State Beavers', 'cfb');
INSERT INTO team_name_map VALUES ('Penn State Nittany Lions', 'Penn State Nittany Lions', 'cfb');
INSERT INTO team_name_map VALUES ('Pittsburgh Panthers', 'Pittsburgh Panthers', 'cfb');
INSERT INTO team_name_map VALUES ('Portland State Vikings', 'Portland State Vikings', 'cfb');
INSERT INTO team_name_map VALUES ('Prairie View A&M Panthers', 'Prairie View A&M Panthers', 'cfb');
INSERT INTO team_name_map VALUES ('Purdue Boilermakers', 'Purdue Boilermakers', 'cfb');
INSERT INTO team_name_map VALUES ('Rice Owls', 'Rice Owls', 'cfb');
INSERT INTO team_name_map VALUES ('Richmond Spiders', 'Richmond Spiders', 'cfb');
INSERT INTO team_name_map VALUES ('Robert Morris Colonials', 'Robert Morris Colonials', 'cfb');
INSERT INTO team_name_map VALUES ('Rutgers Scarlet Knights', 'Rutgers Scarlet Knights', 'cfb');
INSERT INTO team_name_map VALUES ('SMU Mustangs', 'SMU Mustangs', 'cfb');
INSERT INTO team_name_map VALUES ('Sam Houston State Bearkats', 'Houston Cougars', 'cfb');
INSERT INTO team_name_map VALUES ('San Diego State Aztecs', 'San Diego State Aztecs', 'cfb');
INSERT INTO team_name_map VALUES ('South Alabama Jaguars', 'South Alabama Jaguars', 'cfb');
INSERT INTO team_name_map VALUES ('South Carolina Gamecocks', 'South Carolina Gamecocks', 'cfb');
INSERT INTO team_name_map VALUES ('South Carolina State Bulldogs', 'South Carolina State Bulldogs', 'cfb');
INSERT INTO team_name_map VALUES ('South Dakota State Jackrabbits', 'South Dakota State Jackrabbits', 'cfb');
INSERT INTO team_name_map VALUES ('South Florida Bulls', 'South Florida Bulls', 'cfb');
INSERT INTO team_name_map VALUES ('Southeast Missouri State Redhawks', 'Southeast Missouri State Redhawks', 'cfb');
INSERT INTO team_name_map VALUES ('Southern Illinois Salukis', 'Southern Illinois Salukis', 'cfb');
INSERT INTO team_name_map VALUES ('Southern Mississippi Golden Eagles', 'Southern Miss Golden Eagles', 'cfb');
INSERT INTO team_name_map VALUES ('Stanford Cardinal', 'Stanford Cardinal', 'cfb');
INSERT INTO team_name_map VALUES ('Stony Brook Seawolves', 'Stony Brook Seawolves', 'cfb');
INSERT INTO team_name_map VALUES ('Syracuse Orange', 'Syracuse Orange', 'cfb');
INSERT INTO team_name_map VALUES ('TCU Horned Frogs', 'TCU Horned Frogs', 'cfb');
INSERT INTO team_name_map VALUES ('Tarleton State Texans', 'Tarleton State Texans', 'cfb');
INSERT INTO team_name_map VALUES ('Temple Owls', 'Temple Owls', 'cfb');
INSERT INTO team_name_map VALUES ('Tennessee State Tigers', 'Tennessee State Tigers', 'cfb');
INSERT INTO team_name_map VALUES ('Tennessee Tech Golden Eagles', 'Tennessee Tech Golden Eagles', 'cfb');
INSERT INTO team_name_map VALUES ('Tennessee Volunteers', 'Tennessee Volunteers', 'cfb');
INSERT INTO team_name_map VALUES ('Texas A&M Aggies', 'Texas A&M Aggies', 'cfb');
INSERT INTO team_name_map VALUES ('Texas A&M-Commerce Lions', 'Texas A&M Aggies', 'cfb');
INSERT INTO team_name_map VALUES ('Texas Longhorns', 'Texas Longhorns', 'cfb');
INSERT INTO team_name_map VALUES ('Texas State Bobcats', 'Texas State Bobcats', 'cfb');
INSERT INTO team_name_map VALUES ('Texas Tech Red Raiders', 'Texas Tech Red Raiders', 'cfb');
INSERT INTO team_name_map VALUES ('Toledo Rockets', 'Toledo Rockets', 'cfb');
INSERT INTO team_name_map VALUES ('Towson Tigers', 'Towson Tigers', 'cfb');
INSERT INTO team_name_map VALUES ('Troy Trojans', 'Troy Trojans', 'cfb');
INSERT INTO team_name_map VALUES ('Tulane Green Wave', 'Tulane Green Wave', 'cfb');
INSERT INTO team_name_map VALUES ('Tulsa Golden Hurricane', 'Tulsa Golden Hurricane', 'cfb');
INSERT INTO team_name_map VALUES ('UAB Blazers', 'UAB Blazers', 'cfb');
INSERT INTO team_name_map VALUES ('UC Davis Aggies', 'UC Davis Aggies', 'cfb');
INSERT INTO team_name_map VALUES ('UCF Knights', 'UCF Knights', 'cfb');
INSERT INTO team_name_map VALUES ('UCLA Bruins', 'UCLA Bruins', 'cfb');
INSERT INTO team_name_map VALUES ('UConn Huskies', 'UConn Huskies', 'cfb');
INSERT INTO team_name_map VALUES ('UL Monroe Warhawks', 'UL Monroe Warhawks', 'cfb');
INSERT INTO team_name_map VALUES ('UMass Minutemen', 'UMass Dartmouth Corsairs', 'cfb');
INSERT INTO team_name_map VALUES ('UNLV Rebels', 'UNLV Rebels', 'cfb');
INSERT INTO team_name_map VALUES ('USC Trojans', 'USC Trojans', 'cfb');
INSERT INTO team_name_map VALUES ('UT Martin Skyhawks', 'UT Martin Skyhawks', 'cfb');
INSERT INTO team_name_map VALUES ('UTEP Miners', 'UTEP Miners', 'cfb');
INSERT INTO team_name_map VALUES ('UTSA Roadrunners', 'UTSA Roadrunners', 'cfb');
INSERT INTO team_name_map VALUES ('Utah State Aggies', 'Utah State Aggies', 'cfb');
INSERT INTO team_name_map VALUES ('Utah Utes', 'Utah Utes', 'cfb');
INSERT INTO team_name_map VALUES ('VMI Keydets', 'VMI Keydets', 'cfb');
INSERT INTO team_name_map VALUES ('Vanderbilt Commodores', 'Vanderbilt Commodores', 'cfb');
INSERT INTO team_name_map VALUES ('Virginia Cavaliers', 'Virginia Cavaliers', 'cfb');
INSERT INTO team_name_map VALUES ('Virginia Tech Hokies', 'Virginia Tech Hokies', 'cfb');
INSERT INTO team_name_map VALUES ('Wagner Seahawks', 'Wagner Seahawks', 'cfb');
INSERT INTO team_name_map VALUES ('Wake Forest Demon Deacons', 'Wake Forest Demon Deacons', 'cfb');
INSERT INTO team_name_map VALUES ('Washington Huskies', 'Washington Huskies', 'cfb');
INSERT INTO team_name_map VALUES ('Washington State Cougars', 'Washington State Cougars', 'cfb');
INSERT INTO team_name_map VALUES ('Weber State Wildcats', 'Weber State Wildcats', 'cfb');
INSERT INTO team_name_map VALUES ('West Virginia Mountaineers', 'West Virginia Mountaineers', 'cfb');
INSERT INTO team_name_map VALUES ('Western Illinois Leathernecks', 'Western Illinois Leathernecks', 'cfb');
INSERT INTO team_name_map VALUES ('Western Kentucky Hilltoppers', 'Western Kentucky Hilltoppers', 'cfb');
INSERT INTO team_name_map VALUES ('Western Michigan Broncos', 'Western Michigan Broncos', 'cfb');
INSERT INTO team_name_map VALUES ('Wisconsin Badgers', 'Wisconsin Badgers', 'cfb');
INSERT INTO team_name_map VALUES ('Wofford Terriers', 'Wofford Terriers', 'cfb');
INSERT INTO team_name_map VALUES ('Wyoming Cowboys', 'Wyoming Cowboys', 'cfb');
INSERT INTO team_name_map VALUES ('Atlanta Hawks', 'Atlanta Hawks', 'nba');
INSERT INTO team_name_map VALUES ('Boston Celtics', 'Boston Celtics', 'nba');
INSERT INTO team_name_map VALUES ('Brooklyn Nets', 'Brooklyn Nets', 'nba');
INSERT INTO team_name_map VALUES ('Charlotte Hornets', 'Charlotte Hornets', 'nba');
INSERT INTO team_name_map VALUES ('Chicago Bulls', 'Chicago Bulls', 'nba');
INSERT INTO team_name_map VALUES ('Cleveland Cavaliers', 'Cleveland Cavaliers', 'nba');
INSERT INTO team_name_map VALUES ('Dallas Mavericks', 'Dallas Mavericks', 'nba');
INSERT INTO team_name_map VALUES ('Denver Nuggets', 'Denver Nuggets', 'nba');
INSERT INTO team_name_map VALUES ('Detroit Pistons', 'Detroit Pistons', 'nba');
INSERT INTO team_name_map VALUES ('Golden State Warriors', 'Golden State Warriors', 'nba');
INSERT INTO team_name_map VALUES ('Houston Rockets', 'Houston Rockets', 'nba');
INSERT INTO team_name_map VALUES ('Indiana Pacers', 'Indiana Pacers', 'nba');
INSERT INTO team_name_map VALUES ('Los Angeles Clippers', 'Los Angeles Lakers', 'nba');
INSERT INTO team_name_map VALUES ('Los Angeles Lakers', 'Los Angeles Lakers', 'nba');
INSERT INTO team_name_map VALUES ('Memphis Grizzlies', 'Memphis Grizzlies', 'nba');
INSERT INTO team_name_map VALUES ('Miami Heat', 'Miami Heat', 'nba');
INSERT INTO team_name_map VALUES ('Milwaukee Bucks', 'Milwaukee Bucks', 'nba');
INSERT INTO team_name_map VALUES ('Minnesota Timberwolves', 'Minnesota Timberwolves', 'nba');
INSERT INTO team_name_map VALUES ('New Orleans Pelicans', 'New Orleans Pelicans', 'nba');
INSERT INTO team_name_map VALUES ('New York Knicks', 'New York Knicks', 'nba');
INSERT INTO team_name_map VALUES ('Oklahoma City Thunder', 'Oklahoma City Thunder', 'nba');
INSERT INTO team_name_map VALUES ('Orlando Magic', 'Orlando Magic', 'nba');
INSERT INTO team_name_map VALUES ('Philadelphia 76ers', 'Philadelphia 76ers', 'nba');
INSERT INTO team_name_map VALUES ('Phoenix Suns', 'Phoenix Suns', 'nba');
INSERT INTO team_name_map VALUES ('Portland Trail Blazers', 'Portland Trail Blazers', 'nba');
INSERT INTO team_name_map VALUES ('Sacramento Kings', 'Sacramento Kings', 'nba');
INSERT INTO team_name_map VALUES ('San Antonio Spurs', 'San Antonio Spurs', 'nba');
INSERT INTO team_name_map VALUES ('Toronto Raptors', 'Toronto Raptors', 'nba');
INSERT INTO team_name_map VALUES ('Utah Jazz', 'Utah Jazz', 'nba');
INSERT INTO team_name_map VALUES ('Washington Wizards', 'Washington Wizards', 'nba');
INSERT INTO team_name_map VALUES ('Abilene Christian Wildcats', 'Abilene Christian Wildcats', 'cbb');
INSERT INTO team_name_map VALUES ('Air Force Falcons', 'Air Force Falcons', 'cbb');
INSERT INTO team_name_map VALUES ('Akron Zips', 'Akron Zips', 'cbb');
INSERT INTO team_name_map VALUES ('Alabama A&M Bulldogs', 'Alabama A&M Bulldogs', 'cbb');
INSERT INTO team_name_map VALUES ('Alabama Crimson Tide', 'Alabama Crimson Tide', 'cbb');
INSERT INTO team_name_map VALUES ('Alabama St Hornets', 'Alabama State Hornets', 'cbb');
INSERT INTO team_name_map VALUES ('Albany Great Danes', 'UAlbany Great Danes', 'cbb');
INSERT INTO team_name_map VALUES ('Alcorn St Braves', 'Alcorn State Braves', 'cbb');
INSERT INTO team_name_map VALUES ('American Eagles', 'American University Eagles', 'cbb');
INSERT INTO team_name_map VALUES ('Arizona St Sun Devils', 'Arizona State Sun Devils', 'cbb');
INSERT INTO team_name_map VALUES ('Arizona Wildcats', 'Arizona Wildcats', 'cbb');
INSERT INTO team_name_map VALUES ('Arkansas Razorbacks', 'Arkansas Razorbacks', 'cbb');
INSERT INTO team_name_map VALUES ('Arkansas St Red Wolves', 'Arkansas State Red Wolves', 'cbb');
INSERT INTO team_name_map VALUES ('Arkansas-Little Rock Trojans', 'Little Rock Trojans', 'cbb');
INSERT INTO team_name_map VALUES ('Arkansas-Pine Bluff Golden Lions', 'Arkansas-Pine Bluff Golden Lions', 'cbb');
INSERT INTO team_name_map VALUES ('Army Knights', 'Army Black Knights', 'cbb');
INSERT INTO team_name_map VALUES ('Auburn Tigers', 'Auburn Tigers', 'cbb');
INSERT INTO team_name_map VALUES ('Austin Peay Governors', 'Austin Peay Governors', 'cbb');
INSERT INTO team_name_map VALUES ('BYU Cougars', 'BYU Cougars', 'cbb');
INSERT INTO team_name_map VALUES ('Ball State Cardinals', 'Ball State Cardinals', 'cbb');
INSERT INTO team_name_map VALUES ('Baylor Bears', 'Baylor Bears', 'cbb');
INSERT INTO team_name_map VALUES ('Bellarmine Knights', 'Bellarmine Knights', 'cbb');
INSERT INTO team_name_map VALUES ('Belmont Bruins', 'Belmont Bruins', 'cbb');
INSERT INTO team_name_map VALUES ('Bethune-Cookman Wildcats', 'Bethune-Cookman Wildcats', 'cbb');
INSERT INTO team_name_map VALUES ('Binghamton Bearcats', 'Binghamton Bearcats', 'cbb');
INSERT INTO team_name_map VALUES ('Boise State Broncos', 'Boise State Broncos', 'cbb');
INSERT INTO team_name_map VALUES ('Boston College Eagles', 'Boston College Eagles', 'cbb');
INSERT INTO team_name_map VALUES ('Boston Univ. Terriers', 'Boston University Terriers', 'cbb');
INSERT INTO team_name_map VALUES ('Bowling Green Falcons', 'Bowling Green Falcons', 'cbb');
INSERT INTO team_name_map VALUES ('Bradley Braves', 'Bradley Braves', 'cbb');
INSERT INTO team_name_map VALUES ('Brown Bears', 'Brown Bears', 'cbb');
INSERT INTO team_name_map VALUES ('Bryant Bulldogs', 'Bryant Bulldogs', 'cbb');
INSERT INTO team_name_map VALUES ('Bucknell Bison', 'Bucknell Bison', 'cbb');
INSERT INTO team_name_map VALUES ('Buffalo Bulls', 'Buffalo Bulls', 'cbb');
INSERT INTO team_name_map VALUES ('Butler Bulldogs', 'Butler Bulldogs', 'cbb');
INSERT INTO team_name_map VALUES ('Cal Poly Mustangs', 'Cal Poly Mustangs', 'cbb');
INSERT INTO team_name_map VALUES ('California Golden Bears', 'California Golden Bears', 'cbb');
INSERT INTO team_name_map VALUES ('Campbell Fighting Camels', 'Campbell Fighting Camels', 'cbb');
INSERT INTO team_name_map VALUES ('Canisius Golden Griffins', 'Canisius Golden Griffins', 'cbb');
INSERT INTO team_name_map VALUES ('Central Arkansas Bears', 'Central Arkansas Bears', 'cbb');
INSERT INTO team_name_map VALUES ('Central Michigan Chippewas', 'Central Michigan Chippewas', 'cbb');
INSERT INTO team_name_map VALUES ('Charleston Cougars', 'Charleston Cougars', 'cbb');
INSERT INTO team_name_map VALUES ('Charleston Southern Buccaneers', 'Charleston Southern Buccaneers', 'cbb');
INSERT INTO team_name_map VALUES ('Charlotte 49ers', 'Charlotte 49ers', 'cbb');
INSERT INTO team_name_map VALUES ('Chattanooga Mocs', 'Chattanooga Mocs', 'cbb');
INSERT INTO team_name_map VALUES ('Chicago St Cougars', 'Chicago State Cougars', 'cbb');
INSERT INTO team_name_map VALUES ('Cincinnati Bearcats', 'Cincinnati Bearcats', 'cbb');
INSERT INTO team_name_map VALUES ('Clemson Tigers', 'Clemson Tigers', 'cbb');
INSERT INTO team_name_map VALUES ('Cleveland St Vikings', 'Cleveland State Vikings', 'cbb');
INSERT INTO team_name_map VALUES ('Coastal Carolina Chanticleers', 'Coastal Carolina Chanticleers', 'cbb');
INSERT INTO team_name_map VALUES ('Colgate Raiders', 'Colgate Raiders', 'cbb');
INSERT INTO team_name_map VALUES ('Colorado Buffaloes', 'Colorado Buffaloes', 'cbb');
INSERT INTO team_name_map VALUES ('Colorado St Rams', 'Colorado State Rams', 'cbb');
INSERT INTO team_name_map VALUES ('Columbia Lions', 'Columbia Lions', 'cbb');
INSERT INTO team_name_map VALUES ('Coppin St Eagles', 'Coppin State Eagles', 'cbb');
INSERT INTO team_name_map VALUES ('Cornell Big Red', 'Cornell Big Red', 'cbb');
INSERT INTO team_name_map VALUES ('Creighton Bluejays', 'Creighton Bluejays', 'cbb');
INSERT INTO team_name_map VALUES ('Dartmouth Big Green', 'Dartmouth Big Green', 'cbb');
INSERT INTO team_name_map VALUES ('Davidson Wildcats', 'Davidson Wildcats', 'cbb');
INSERT INTO team_name_map VALUES ('Dayton Flyers', 'Dayton Flyers', 'cbb');
INSERT INTO team_name_map VALUES ('DePaul Blue Demons', 'DePaul Blue Demons', 'cbb');
INSERT INTO team_name_map VALUES ('Delaware Blue Hens', 'Delaware Blue Hens', 'cbb');
INSERT INTO team_name_map VALUES ('Delaware St Hornets', 'Delaware State Hornets', 'cbb');
INSERT INTO team_name_map VALUES ('Denver Pioneers', 'Denver Pioneers', 'cbb');
INSERT INTO team_name_map VALUES ('Detroit Mercy Titans', 'Detroit Mercy Titans', 'cbb');
INSERT INTO team_name_map VALUES ('Drake Bulldogs', 'Drake Bulldogs', 'cbb');
INSERT INTO team_name_map VALUES ('Drexel Dragons', 'Drexel Dragons', 'cbb');
INSERT INTO team_name_map VALUES ('Duke Blue Devils', 'Duke Blue Devils', 'cbb');
INSERT INTO team_name_map VALUES ('Duquesne Dukes', 'Duquesne Dukes', 'cbb');
INSERT INTO team_name_map VALUES ('East Carolina Pirates', 'East Carolina Pirates', 'cbb');
INSERT INTO team_name_map VALUES ('East Tennessee St Buccaneers', 'East Tennessee State Buccaneers', 'cbb');
INSERT INTO team_name_map VALUES ('Eastern Illinois Panthers', 'Eastern Illinois Panthers', 'cbb');
INSERT INTO team_name_map VALUES ('Eastern Kentucky Colonels', 'Eastern Kentucky Colonels', 'cbb');
INSERT INTO team_name_map VALUES ('Eastern Michigan Eagles', 'Eastern Michigan Eagles', 'cbb');
INSERT INTO team_name_map VALUES ('Eastern Washington Eagles', 'Eastern Washington Eagles', 'cbb');
INSERT INTO team_name_map VALUES ('Elon Phoenix', 'Elon Phoenix', 'cbb');
INSERT INTO team_name_map VALUES ('Evansville Purple Aces', 'Evansville Purple Aces', 'cbb');
INSERT INTO team_name_map VALUES ('Fairfield Stags', 'Fairfield Stags', 'cbb');
INSERT INTO team_name_map VALUES ('Fairleigh Dickinson Knights', 'Fairleigh Dickinson Knights', 'cbb');
INSERT INTO team_name_map VALUES ('Florida A&M Rattlers', 'Florida A&M Rattlers', 'cbb');
INSERT INTO team_name_map VALUES ('Florida Atlantic Owls', 'Florida Atlantic Owls', 'cbb');
INSERT INTO team_name_map VALUES ('Florida Gators', 'Florida Gators', 'cbb');
INSERT INTO team_name_map VALUES ('Florida Gulf Coast Eagles', 'Florida Gulf Coast Eagles', 'cbb');
INSERT INTO team_name_map VALUES ('Florida Int''l Golden Panthers', 'Florida Gators', 'cbb');
INSERT INTO team_name_map VALUES ('Florida St Seminoles', 'Florida State Seminoles', 'cbb');
INSERT INTO team_name_map VALUES ('Fordham Rams', 'Fordham Rams', 'cbb');
INSERT INTO team_name_map VALUES ('Fort Wayne Mastodons', 'Purdue Fort Wayne Mastodons', 'cbb');
INSERT INTO team_name_map VALUES ('Fresno St Bulldogs', 'Fresno State Bulldogs', 'cbb');
INSERT INTO team_name_map VALUES ('Furman Paladins', 'Furman Paladins', 'cbb');
INSERT INTO team_name_map VALUES ('GW Revolutionaries', 'Longwood Lancers', 'cbb');
INSERT INTO team_name_map VALUES ('Gardner-Webb Bulldogs', 'Gardner-Webb Runnin'' Bulldogs', 'cbb');
INSERT INTO team_name_map VALUES ('George Mason Patriots', 'George Mason Patriots', 'cbb');
INSERT INTO team_name_map VALUES ('Georgetown Hoyas', 'Georgetown Hoyas', 'cbb');
INSERT INTO team_name_map VALUES ('Georgia Bulldogs', 'Georgia Bulldogs', 'cbb');
INSERT INTO team_name_map VALUES ('Georgia Southern Eagles', 'Georgia Southern Eagles', 'cbb');
INSERT INTO team_name_map VALUES ('Georgia St Panthers', 'Georgia State Panthers', 'cbb');
INSERT INTO team_name_map VALUES ('Georgia Tech Yellow Jackets', 'Georgia Tech Yellow Jackets', 'cbb');
INSERT INTO team_name_map VALUES ('Gonzaga Bulldogs', 'Gonzaga Bulldogs', 'cbb');
INSERT INTO team_name_map VALUES ('Grambling St Tigers', 'Grambling Tigers', 'cbb');
INSERT INTO team_name_map VALUES ('Grand Canyon Antelopes', 'Grand Canyon Lopes', 'cbb');
INSERT INTO team_name_map VALUES ('Green Bay Phoenix', 'Green Bay Phoenix', 'cbb');
INSERT INTO team_name_map VALUES ('Hampton Pirates', 'Hampton Pirates', 'cbb');
INSERT INTO team_name_map VALUES ('Harvard Crimson', 'Harvard Crimson', 'cbb');
INSERT INTO team_name_map VALUES ('Hawai''i Rainbow Warriors', 'Hawai''i Rainbow Warriors', 'cbb');
INSERT INTO team_name_map VALUES ('High Point Panthers', 'High Point Panthers', 'cbb');
INSERT INTO team_name_map VALUES ('Hofstra Pride', 'Hofstra Pride', 'cbb');
INSERT INTO team_name_map VALUES ('Holy Cross Crusaders', 'Holy Cross Crusaders', 'cbb');
INSERT INTO team_name_map VALUES ('Houston Christian Huskies', 'Houston Christian Huskies', 'cbb');
INSERT INTO team_name_map VALUES ('Houston Cougars', 'Houston Cougars', 'cbb');
INSERT INTO team_name_map VALUES ('Howard Bison', 'Howard Bison', 'cbb');
INSERT INTO team_name_map VALUES ('Idaho State Bengals', 'Idaho State Bengals', 'cbb');
INSERT INTO team_name_map VALUES ('Idaho Vandals', 'Idaho Vandals', 'cbb');
INSERT INTO team_name_map VALUES ('Illinois Fighting Illini', 'Illinois Fighting Illini', 'cbb');
INSERT INTO team_name_map VALUES ('Illinois St Redbirds', 'Illinois State Redbirds', 'cbb');
INSERT INTO team_name_map VALUES ('Incarnate Word Cardinals', 'Incarnate Word Cardinals', 'cbb');
INSERT INTO team_name_map VALUES ('Indiana Hoosiers', 'Indiana Hoosiers', 'cbb');
INSERT INTO team_name_map VALUES ('Indiana St Sycamores', 'Indiana State Sycamores', 'cbb');
INSERT INTO team_name_map VALUES ('Iona Gaels', 'Iona Gaels', 'cbb');
INSERT INTO team_name_map VALUES ('Iowa Hawkeyes', 'Iowa Hawkeyes', 'cbb');
INSERT INTO team_name_map VALUES ('Iowa State Cyclones', 'Iowa State Cyclones', 'cbb');
INSERT INTO team_name_map VALUES ('Jackson St Tigers', 'Jackson State Tigers', 'cbb');
INSERT INTO team_name_map VALUES ('Jacksonville Dolphins', 'Jacksonville Dolphins', 'cbb');
INSERT INTO team_name_map VALUES ('Jacksonville St Gamecocks', 'Jacksonville State Gamecocks', 'cbb');
INSERT INTO team_name_map VALUES ('James Madison Dukes', 'James Madison Dukes', 'cbb');
INSERT INTO team_name_map VALUES ('Kansas Jayhawks', 'Kansas Jayhawks', 'cbb');
INSERT INTO team_name_map VALUES ('Kansas St Wildcats', 'Kansas State Wildcats', 'cbb');
INSERT INTO team_name_map VALUES ('Kennesaw St Owls', 'Kennesaw State Owls', 'cbb');
INSERT INTO team_name_map VALUES ('Kent State Golden Flashes', 'Kent State Golden Flashes', 'cbb');
INSERT INTO team_name_map VALUES ('Kentucky Wildcats', 'Kentucky Wildcats', 'cbb');
INSERT INTO team_name_map VALUES ('LSU Tigers', 'LSU Tigers', 'cbb');
INSERT INTO team_name_map VALUES ('La Salle Explorers', 'La Salle Explorers', 'cbb');
INSERT INTO team_name_map VALUES ('Lafayette Leopards', 'Lafayette Leopards', 'cbb');
INSERT INTO team_name_map VALUES ('Lamar Cardinals', 'Lamar Cardinals', 'cbb');
INSERT INTO team_name_map VALUES ('Le Moyne Dolphins', 'Le Moyne Dolphins', 'cbb');
INSERT INTO team_name_map VALUES ('Lehigh Mountain Hawks', 'Lehigh Mountain Hawks', 'cbb');
INSERT INTO team_name_map VALUES ('Liberty Flames', 'Liberty Flames', 'cbb');
INSERT INTO team_name_map VALUES ('Lindenwood Lions', 'Lindenwood Lions', 'cbb');
INSERT INTO team_name_map VALUES ('Lipscomb Bisons', 'Lipscomb Bisons', 'cbb');
INSERT INTO team_name_map VALUES ('Long Beach St 49ers', 'Long Beach State Beach', 'cbb');
INSERT INTO team_name_map VALUES ('Longwood Lancers', 'Longwood Lancers', 'cbb');
INSERT INTO team_name_map VALUES ('Louisiana Ragin'' Cajuns', 'Louisiana Ragin'' Cajuns', 'cbb');
INSERT INTO team_name_map VALUES ('Louisiana Tech Bulldogs', 'Louisiana Tech Bulldogs', 'cbb');
INSERT INTO team_name_map VALUES ('Louisville Cardinals', 'Louisville Cardinals', 'cbb');
INSERT INTO team_name_map VALUES ('Loyola (Chi) Ramblers', 'Loyola Chicago Ramblers', 'cbb');
INSERT INTO team_name_map VALUES ('Loyola Marymount Lions', 'Loyola Marymount Lions', 'cbb');
INSERT INTO team_name_map VALUES ('Maine Black Bears', 'Maine Black Bears', 'cbb');
INSERT INTO team_name_map VALUES ('Manhattan Jaspers', 'Manhattan Jaspers', 'cbb');
INSERT INTO team_name_map VALUES ('Marist Red Foxes', 'Marist Red Foxes', 'cbb');
INSERT INTO team_name_map VALUES ('Marquette Golden Eagles', 'Marquette Golden Eagles', 'cbb');
INSERT INTO team_name_map VALUES ('Marshall Thundering Herd', 'Marshall Thundering Herd', 'cbb');
INSERT INTO team_name_map VALUES ('Maryland Terrapins', 'Maryland Terrapins', 'cbb');
INSERT INTO team_name_map VALUES ('Maryland-Eastern Shore Hawks', 'Maryland Terrapins', 'cbb');
INSERT INTO team_name_map VALUES ('Massachusetts Minutemen', 'Massachusetts Minutemen', 'cbb');
INSERT INTO team_name_map VALUES ('McNeese Cowboys', 'McNeese Cowboys', 'cbb');
INSERT INTO team_name_map VALUES ('Memphis Tigers', 'Memphis Tigers', 'cbb');
INSERT INTO team_name_map VALUES ('Mercer Bears', 'Mercer Bears', 'cbb');
INSERT INTO team_name_map VALUES ('Mercyhurst Lakers', 'Mercyhurst Lakers', 'cbb');
INSERT INTO team_name_map VALUES ('Merrimack Warriors', 'Merrimack Warriors', 'cbb');
INSERT INTO team_name_map VALUES ('Miami (OH) RedHawks', 'Miami (OH) RedHawks', 'cbb');
INSERT INTO team_name_map VALUES ('Miami Hurricanes', 'Miami Hurricanes', 'cbb');
INSERT INTO team_name_map VALUES ('Michigan St Spartans', 'Michigan State Spartans', 'cbb');
INSERT INTO team_name_map VALUES ('Michigan Wolverines', 'Michigan Wolverines', 'cbb');
INSERT INTO team_name_map VALUES ('Middle Tennessee Blue Raiders', 'Middle Tennessee Blue Raiders', 'cbb');
INSERT INTO team_name_map VALUES ('Milwaukee Panthers', 'Milwaukee Panthers', 'cbb');
INSERT INTO team_name_map VALUES ('Minnesota Golden Gophers', 'Minnesota Golden Gophers', 'cbb');
INSERT INTO team_name_map VALUES ('Miss Valley St Delta Devils', 'Mississippi Valley State Delta Devils', 'cbb');
INSERT INTO team_name_map VALUES ('Mississippi St Bulldogs', 'Mississippi State Bulldogs', 'cbb');
INSERT INTO team_name_map VALUES ('Missouri St Bears', 'Missouri State Bears', 'cbb');
INSERT INTO team_name_map VALUES ('Missouri Tigers', 'Missouri Tigers', 'cbb');
INSERT INTO team_name_map VALUES ('Monmouth Hawks', 'Monmouth Hawks', 'cbb');
INSERT INTO team_name_map VALUES ('Montana Grizzlies', 'Montana Grizzlies', 'cbb');
INSERT INTO team_name_map VALUES ('Montana St Bobcats', 'Montana State Bobcats', 'cbb');
INSERT INTO team_name_map VALUES ('Morehead St Eagles', 'Morehead State Eagles', 'cbb');
INSERT INTO team_name_map VALUES ('Morgan St Bears', 'Morgan State Bears', 'cbb');
INSERT INTO team_name_map VALUES ('Mt. St. Mary''s Mountaineers', 'Mount St. Mary''s Mountaineers', 'cbb');
INSERT INTO team_name_map VALUES ('Murray St Racers', 'Murray State Racers', 'cbb');
INSERT INTO team_name_map VALUES ('N Colorado Bears', 'Northern Colorado Bears', 'cbb');
INSERT INTO team_name_map VALUES ('NC State Wolfpack', 'NC State Wolfpack', 'cbb');
INSERT INTO team_name_map VALUES ('NJIT Highlanders', 'NJIT Highlanders', 'cbb');
INSERT INTO team_name_map VALUES ('Navy Midshipmen', 'Navy Midshipmen', 'cbb');
INSERT INTO team_name_map VALUES ('Nebraska Cornhuskers', 'Nebraska Cornhuskers', 'cbb');
INSERT INTO team_name_map VALUES ('Nevada Wolf Pack', 'Nevada Wolf Pack', 'cbb');
INSERT INTO team_name_map VALUES ('New Hampshire Wildcats', 'New Hampshire Wildcats', 'cbb');
INSERT INTO team_name_map VALUES ('New Mexico Lobos', 'New Mexico Lobos', 'cbb');
INSERT INTO team_name_map VALUES ('New Mexico St Aggies', 'New Mexico State Aggies', 'cbb');
INSERT INTO team_name_map VALUES ('New Orleans Privateers', 'New Orleans Privateers', 'cbb');
INSERT INTO team_name_map VALUES ('Niagara Purple Eagles', 'Niagara Purple Eagles', 'cbb');
INSERT INTO team_name_map VALUES ('Nicholls St Colonels', 'Nicholls Colonels', 'cbb');
INSERT INTO team_name_map VALUES ('Norfolk St Spartans', 'Norfolk State Spartans', 'cbb');
INSERT INTO team_name_map VALUES ('North Alabama Lions', 'North Alabama Lions', 'cbb');
INSERT INTO team_name_map VALUES ('North Carolina A&T Aggies', 'North Carolina A&T Aggies', 'cbb');
INSERT INTO team_name_map VALUES ('North Carolina Central Eagles', 'North Carolina Central Eagles', 'cbb');
INSERT INTO team_name_map VALUES ('North Carolina Tar Heels', 'North Carolina Tar Heels', 'cbb');
INSERT INTO team_name_map VALUES ('North Dakota Fighting Hawks', 'North Dakota Fighting Hawks', 'cbb');
INSERT INTO team_name_map VALUES ('North Dakota St Bison', 'North Dakota State Bison', 'cbb');
INSERT INTO team_name_map VALUES ('North Florida Ospreys', 'North Florida Ospreys', 'cbb');
INSERT INTO team_name_map VALUES ('North Texas Mean Green', 'North Texas Mean Green', 'cbb');
INSERT INTO team_name_map VALUES ('Northeastern Huskies', 'Northeastern Huskies', 'cbb');
INSERT INTO team_name_map VALUES ('Northern Arizona Lumberjacks', 'Northern Arizona Lumberjacks', 'cbb');
INSERT INTO team_name_map VALUES ('Northern Illinois Huskies', 'Northern Illinois Huskies', 'cbb');
INSERT INTO team_name_map VALUES ('Northern Iowa Panthers', 'Northern Iowa Panthers', 'cbb');
INSERT INTO team_name_map VALUES ('Northern Kentucky Norse', 'Northern Kentucky Norse', 'cbb');
INSERT INTO team_name_map VALUES ('Northwestern St Demons', 'Northwestern State Demons', 'cbb');
INSERT INTO team_name_map VALUES ('Northwestern Wildcats', 'Northwestern Wildcats', 'cbb');
INSERT INTO team_name_map VALUES ('Notre Dame Fighting Irish', 'Notre Dame Fighting Irish', 'cbb');
INSERT INTO team_name_map VALUES ('Oakland Golden Grizzlies', 'Oakland Golden Grizzlies', 'cbb');
INSERT INTO team_name_map VALUES ('Ohio Bobcats', 'Ohio Bobcats', 'cbb');
INSERT INTO team_name_map VALUES ('Ohio State Buckeyes', 'Ohio State Buckeyes', 'cbb');
INSERT INTO team_name_map VALUES ('Oklahoma Sooners', 'Oklahoma Sooners', 'cbb');
INSERT INTO team_name_map VALUES ('Oklahoma St Cowboys', 'Oklahoma State Cowboys', 'cbb');
INSERT INTO team_name_map VALUES ('Old Dominion Monarchs', 'Old Dominion Monarchs', 'cbb');
INSERT INTO team_name_map VALUES ('Ole Miss Rebels', 'Ole Miss Rebels', 'cbb');
INSERT INTO team_name_map VALUES ('Omaha Mavericks', 'Omaha Mavericks', 'cbb');
INSERT INTO team_name_map VALUES ('Oral Roberts Golden Eagles', 'Oral Roberts Golden Eagles', 'cbb');
INSERT INTO team_name_map VALUES ('Oregon Ducks', 'Oregon Ducks', 'cbb');
INSERT INTO team_name_map VALUES ('Oregon St Beavers', 'Oregon State Beavers', 'cbb');
INSERT INTO team_name_map VALUES ('Pacific Tigers', 'Pacific Tigers', 'cbb');
INSERT INTO team_name_map VALUES ('Penn State Nittany Lions', 'Penn State Nittany Lions', 'cbb');
INSERT INTO team_name_map VALUES ('Pennsylvania Quakers', 'Pennsylvania Quakers', 'cbb');
INSERT INTO team_name_map VALUES ('Pepperdine Waves', 'Pepperdine Waves', 'cbb');
INSERT INTO team_name_map VALUES ('Pittsburgh Panthers', 'Pittsburgh Panthers', 'cbb');
INSERT INTO team_name_map VALUES ('Portland Pilots', 'Portland Pilots', 'cbb');
INSERT INTO team_name_map VALUES ('Portland St Vikings', 'Portland State Vikings', 'cbb');
INSERT INTO team_name_map VALUES ('Prairie View Panthers', 'Prairie View A&M Panthers', 'cbb');
INSERT INTO team_name_map VALUES ('Presbyterian Blue Hose', 'Presbyterian Blue Hose', 'cbb');
INSERT INTO team_name_map VALUES ('Princeton Tigers', 'Princeton Tigers', 'cbb');
INSERT INTO team_name_map VALUES ('Providence Friars', 'Providence Friars', 'cbb');
INSERT INTO team_name_map VALUES ('Queens University Royals', 'Queens University Royals', 'cbb');
INSERT INTO team_name_map VALUES ('Quinnipiac Bobcats', 'Quinnipiac Bobcats', 'cbb');
INSERT INTO team_name_map VALUES ('Radford Highlanders', 'Radford Highlanders', 'cbb');
INSERT INTO team_name_map VALUES ('Rhode Island Rams', 'Rhode Island Rams', 'cbb');
INSERT INTO team_name_map VALUES ('Rice Owls', 'Rice Owls', 'cbb');
INSERT INTO team_name_map VALUES ('Richmond Spiders', 'Richmond Spiders', 'cbb');
INSERT INTO team_name_map VALUES ('Rider Broncs', 'Rider Broncs', 'cbb');
INSERT INTO team_name_map VALUES ('Robert Morris Colonials', 'Robert Morris Colonials', 'cbb');
INSERT INTO team_name_map VALUES ('Rutgers Scarlet Knights', 'Rutgers Scarlet Knights', 'cbb');
INSERT INTO team_name_map VALUES ('SE Louisiana Lions', 'SE Louisiana Lions', 'cbb');
INSERT INTO team_name_map VALUES ('SE Missouri St Redhawks', 'Missouri State Bears', 'cbb');
INSERT INTO team_name_map VALUES ('SMU Mustangs', 'SMU Mustangs', 'cbb');
INSERT INTO team_name_map VALUES ('Sacramento St Hornets', 'Sacramento State Hornets', 'cbb');
INSERT INTO team_name_map VALUES ('Sacred Heart Pioneers', 'Sacred Heart Pioneers', 'cbb');
INSERT INTO team_name_map VALUES ('Saint Joseph''s Hawks', 'Saint Joseph''s Hawks', 'cbb');
INSERT INTO team_name_map VALUES ('Saint Louis Billikens', 'Saint Louis Billikens', 'cbb');
INSERT INTO team_name_map VALUES ('Saint Mary''s Gaels', 'Saint Mary''s Gaels', 'cbb');
INSERT INTO team_name_map VALUES ('Saint Peter''s Peacocks', 'Saint Peter''s Peacocks', 'cbb');
INSERT INTO team_name_map VALUES ('Sam Houston St Bearkats', 'Houston Cougars', 'cbb');
INSERT INTO team_name_map VALUES ('Samford Bulldogs', 'Samford Bulldogs', 'cbb');
INSERT INTO team_name_map VALUES ('San Diego St Aztecs', 'San Diego State Aztecs', 'cbb');
INSERT INTO team_name_map VALUES ('San Diego Toreros', 'San Diego Toreros', 'cbb');
INSERT INTO team_name_map VALUES ('San Francisco Dons', 'San Francisco Dons', 'cbb');
INSERT INTO team_name_map VALUES ('San José St Spartans', 'San José State Spartans', 'cbb');
INSERT INTO team_name_map VALUES ('Santa Clara Broncos', 'Santa Clara Broncos', 'cbb');
INSERT INTO team_name_map VALUES ('Seattle Redhawks', 'Seattle U Redhawks', 'cbb');
INSERT INTO team_name_map VALUES ('Seton Hall Pirates', 'Seton Hall Pirates', 'cbb');
INSERT INTO team_name_map VALUES ('Siena Saints', 'Siena Saints', 'cbb');
INSERT INTO team_name_map VALUES ('South Alabama Jaguars', 'South Alabama Jaguars', 'cbb');
INSERT INTO team_name_map VALUES ('South Carolina Gamecocks', 'South Carolina Gamecocks', 'cbb');
INSERT INTO team_name_map VALUES ('South Carolina St Bulldogs', 'South Carolina State Bulldogs', 'cbb');
INSERT INTO team_name_map VALUES ('South Carolina Upstate Spartans', 'South Carolina Upstate Spartans', 'cbb');
INSERT INTO team_name_map VALUES ('South Dakota Coyotes', 'South Dakota Coyotes', 'cbb');
INSERT INTO team_name_map VALUES ('South Dakota St Jackrabbits', 'South Dakota State Jackrabbits', 'cbb');
INSERT INTO team_name_map VALUES ('South Florida Bulls', 'South Florida Bulls', 'cbb');
INSERT INTO team_name_map VALUES ('Southern Illinois Salukis', 'Southern Illinois Salukis', 'cbb');
INSERT INTO team_name_map VALUES ('Southern Indiana Screaming Eagles', 'Southern Indiana Screaming Eagles', 'cbb');
INSERT INTO team_name_map VALUES ('Southern Jaguars', 'Southern Jaguars', 'cbb');
INSERT INTO team_name_map VALUES ('Southern Miss Golden Eagles', 'Southern Miss Golden Eagles', 'cbb');
INSERT INTO team_name_map VALUES ('Southern Utah Thunderbirds', 'Southern Utah Thunderbirds', 'cbb');
INSERT INTO team_name_map VALUES ('St. Bonaventure Bonnies', 'St. Bonaventure Bonnies', 'cbb');
INSERT INTO team_name_map VALUES ('St. John''s Red Storm', 'St. John''s Red Storm', 'cbb');
INSERT INTO team_name_map VALUES ('Stanford Cardinal', 'Stanford Cardinal', 'cbb');
INSERT INTO team_name_map VALUES ('Stephen F. Austin Lumberjacks', 'Stephen F. Austin Lumberjacks', 'cbb');
INSERT INTO team_name_map VALUES ('Stetson Hatters', 'Stetson Hatters', 'cbb');
INSERT INTO team_name_map VALUES ('Stonehill Skyhawks', 'Stonehill Skyhawks', 'cbb');
INSERT INTO team_name_map VALUES ('Stony Brook Seawolves', 'Stony Brook Seawolves', 'cbb');
INSERT INTO team_name_map VALUES ('Syracuse Orange', 'Syracuse Orange', 'cbb');
INSERT INTO team_name_map VALUES ('TCU Horned Frogs', 'TCU Horned Frogs', 'cbb');
INSERT INTO team_name_map VALUES ('Tarleton State Texans', 'Tarleton State Texans', 'cbb');
INSERT INTO team_name_map VALUES ('Temple Owls', 'Temple Owls', 'cbb');
INSERT INTO team_name_map VALUES ('Tennessee St Tigers', 'Tennessee State Tigers', 'cbb');
INSERT INTO team_name_map VALUES ('Tennessee Tech Golden Eagles', 'Tennessee Tech Golden Eagles', 'cbb');
INSERT INTO team_name_map VALUES ('Tennessee Volunteers', 'Tennessee Volunteers', 'cbb');
INSERT INTO team_name_map VALUES ('Texas A&M Aggies', 'Texas A&M Aggies', 'cbb');
INSERT INTO team_name_map VALUES ('Texas A&M-CC Islanders', 'Texas A&M Aggies', 'cbb');
INSERT INTO team_name_map VALUES ('Texas A&M-Commerce Lions', 'Texas A&M Aggies', 'cbb');
INSERT INTO team_name_map VALUES ('Texas Longhorns', 'Texas Longhorns', 'cbb');
INSERT INTO team_name_map VALUES ('Texas Southern Tigers', 'Texas Southern Tigers', 'cbb');
INSERT INTO team_name_map VALUES ('Texas State Bobcats', 'Texas State Bobcats', 'cbb');
INSERT INTO team_name_map VALUES ('Texas Tech Red Raiders', 'Texas Tech Red Raiders', 'cbb');
INSERT INTO team_name_map VALUES ('The Citadel Bulldogs', 'The Citadel Bulldogs', 'cbb');
INSERT INTO team_name_map VALUES ('Toledo Rockets', 'Toledo Rockets', 'cbb');
INSERT INTO team_name_map VALUES ('Towson Tigers', 'Towson Tigers', 'cbb');
INSERT INTO team_name_map VALUES ('Troy Trojans', 'Troy Trojans', 'cbb');
INSERT INTO team_name_map VALUES ('Tulane Green Wave', 'Tulane Green Wave', 'cbb');
INSERT INTO team_name_map VALUES ('Tulsa Golden Hurricane', 'Tulsa Golden Hurricane', 'cbb');
INSERT INTO team_name_map VALUES ('UAB Blazers', 'UAB Blazers', 'cbb');
INSERT INTO team_name_map VALUES ('UC Davis Aggies', 'UC Davis Aggies', 'cbb');
INSERT INTO team_name_map VALUES ('UC Irvine Anteaters', 'UC Irvine Anteaters', 'cbb');
INSERT INTO team_name_map VALUES ('UC Riverside Highlanders', 'UC Riverside Highlanders', 'cbb');
INSERT INTO team_name_map VALUES ('UC San Diego Tritons', 'UC San Diego Tritons', 'cbb');
INSERT INTO team_name_map VALUES ('UC Santa Barbara Gauchos', 'UC Santa Barbara Gauchos', 'cbb');
INSERT INTO team_name_map VALUES ('UCF Knights', 'UCF Knights', 'cbb');
INSERT INTO team_name_map VALUES ('UCLA Bruins', 'UCLA Bruins', 'cbb');
INSERT INTO team_name_map VALUES ('UConn Huskies', 'UConn Huskies', 'cbb');
INSERT INTO team_name_map VALUES ('UIC Flames', 'UIC Flames', 'cbb');
INSERT INTO team_name_map VALUES ('UL Monroe Warhawks', 'UL Monroe Warhawks', 'cbb');
INSERT INTO team_name_map VALUES ('UMBC Retrievers', 'UMBC Retrievers', 'cbb');
INSERT INTO team_name_map VALUES ('UMass Lowell River Hawks', 'UMass Lowell River Hawks', 'cbb');
INSERT INTO team_name_map VALUES ('UNC Asheville Bulldogs', 'UNC Asheville Bulldogs', 'cbb');
INSERT INTO team_name_map VALUES ('UNC Greensboro Spartans', 'UNC Greensboro Spartans', 'cbb');
INSERT INTO team_name_map VALUES ('UNC Wilmington Seahawks', 'UNC Wilmington Seahawks', 'cbb');
INSERT INTO team_name_map VALUES ('UNLV Rebels', 'UNLV Rebels', 'cbb');
INSERT INTO team_name_map VALUES ('USC Trojans', 'USC Trojans', 'cbb');
INSERT INTO team_name_map VALUES ('UT Rio Grande Valley Vaqueros', 'UT Rio Grande Valley Vaqueros', 'cbb');
INSERT INTO team_name_map VALUES ('UTEP Miners', 'UTEP Miners', 'cbb');
INSERT INTO team_name_map VALUES ('UTSA Roadrunners', 'UTSA Roadrunners', 'cbb');
INSERT INTO team_name_map VALUES ('Utah State Aggies', 'Utah State Aggies', 'cbb');
INSERT INTO team_name_map VALUES ('Utah Tech Trailblazers', 'Utah Tech Trailblazers', 'cbb');
INSERT INTO team_name_map VALUES ('Utah Utes', 'Utah Utes', 'cbb');
INSERT INTO team_name_map VALUES ('Utah Valley Wolverines', 'Utah Valley Wolverines', 'cbb');
INSERT INTO team_name_map VALUES ('VCU Rams', 'VCU Rams', 'cbb');
INSERT INTO team_name_map VALUES ('VMI Keydets', 'VMI Keydets', 'cbb');
INSERT INTO team_name_map VALUES ('Valparaiso Beacons', 'Valparaiso Beacons', 'cbb');
INSERT INTO team_name_map VALUES ('Vanderbilt Commodores', 'Vanderbilt Commodores', 'cbb');
INSERT INTO team_name_map VALUES ('Vermont Catamounts', 'Vermont Catamounts', 'cbb');
INSERT INTO team_name_map VALUES ('Villanova Wildcats', 'Villanova Wildcats', 'cbb');
INSERT INTO team_name_map VALUES ('Virginia Cavaliers', 'Virginia Cavaliers', 'cbb');
INSERT INTO team_name_map VALUES ('Virginia Tech Hokies', 'Virginia Tech Hokies', 'cbb');
INSERT INTO team_name_map VALUES ('Wagner Seahawks', 'Wagner Seahawks', 'cbb');
INSERT INTO team_name_map VALUES ('Wake Forest Demon Deacons', 'Wake Forest Demon Deacons', 'cbb');
INSERT INTO team_name_map VALUES ('Washington Huskies', 'Washington Huskies', 'cbb');
INSERT INTO team_name_map VALUES ('Washington St Cougars', 'Washington State Cougars', 'cbb');
INSERT INTO team_name_map VALUES ('Weber State Wildcats', 'Weber State Wildcats', 'cbb');
INSERT INTO team_name_map VALUES ('West Georgia Wolves', 'West Georgia Wolves', 'cbb');
INSERT INTO team_name_map VALUES ('West Virginia Mountaineers', 'West Virginia Mountaineers', 'cbb');
INSERT INTO team_name_map VALUES ('Western Carolina Catamounts', 'Western Carolina Catamounts', 'cbb');
INSERT INTO team_name_map VALUES ('Western Illinois Leathernecks', 'Western Illinois Leathernecks', 'cbb');
INSERT INTO team_name_map VALUES ('Western Kentucky Hilltoppers', 'Western Kentucky Hilltoppers', 'cbb');
INSERT INTO team_name_map VALUES ('Western Michigan Broncos', 'Western Michigan Broncos', 'cbb');
INSERT INTO team_name_map VALUES ('Wichita St Shockers', 'Wichita State Shockers', 'cbb');
INSERT INTO team_name_map VALUES ('William & Mary Tribe', 'William & Mary Tribe', 'cbb');
INSERT INTO team_name_map VALUES ('Winthrop Eagles', 'Winthrop Eagles', 'cbb');
INSERT INTO team_name_map VALUES ('Wisconsin Badgers', 'Wisconsin Badgers', 'cbb');
INSERT INTO team_name_map VALUES ('Wofford Terriers', 'Wofford Terriers', 'cbb');
INSERT INTO team_name_map VALUES ('Wright St Raiders', 'Wright State Raiders', 'cbb');
INSERT INTO team_name_map VALUES ('Wyoming Cowboys', 'Wyoming Cowboys', 'cbb');
INSERT INTO team_name_map VALUES ('Xavier Musketeers', 'Xavier Musketeers', 'cbb');
INSERT INTO team_name_map VALUES ('Yale Bulldogs', 'Yale Bulldogs', 'cbb');
INSERT INTO team_name_map VALUES ('Youngstown St Penguins', 'Youngstown State Penguins', 'cbb');
INSERT INTO team_name_map VALUES ('Arizona Diamondbacks', 'Arizona Diamondbacks', 'mlb');
INSERT INTO team_name_map VALUES ('Atlanta Braves', 'Atlanta Braves', 'mlb');
INSERT INTO team_name_map VALUES ('Baltimore Orioles', 'Baltimore Orioles', 'mlb');
INSERT INTO team_name_map VALUES ('Boston Red Sox', 'Boston Red Sox', 'mlb');
INSERT INTO team_name_map VALUES ('Chicago Cubs', 'Chicago Cubs', 'mlb');
INSERT INTO team_name_map VALUES ('Chicago White Sox', 'Chicago White Sox', 'mlb');
INSERT INTO team_name_map VALUES ('Cincinnati Reds', 'Cincinnati Reds', 'mlb');
INSERT INTO team_name_map VALUES ('Cleveland Guardians', 'Cleveland Guardians', 'mlb');
INSERT INTO team_name_map VALUES ('Colorado Rockies', 'Colorado Rockies', 'mlb');
INSERT INTO team_name_map VALUES ('Detroit Tigers', 'Detroit Tigers', 'mlb');
INSERT INTO team_name_map VALUES ('Houston Astros', 'Houston Astros', 'mlb');
INSERT INTO team_name_map VALUES ('Kansas City Royals', 'Kansas City Royals', 'mlb');
INSERT INTO team_name_map VALUES ('Los Angeles Angels', 'Los Angeles Angels', 'mlb');
INSERT INTO team_name_map VALUES ('Los Angeles Dodgers', 'Los Angeles Dodgers', 'mlb');
INSERT INTO team_name_map VALUES ('Miami Marlins', 'Miami Marlins', 'mlb');
INSERT INTO team_name_map VALUES ('Milwaukee Brewers', 'Milwaukee Brewers', 'mlb');
INSERT INTO team_name_map VALUES ('Minnesota Twins', 'Minnesota Twins', 'mlb');
INSERT INTO team_name_map VALUES ('New York Mets', 'New York Mets', 'mlb');
INSERT INTO team_name_map VALUES ('New York Yankees', 'New York Yankees', 'mlb');
INSERT INTO team_name_map VALUES ('Oakland Athletics', 'Athletics', 'mlb');
INSERT INTO team_name_map VALUES ('Philadelphia Phillies', 'Philadelphia Phillies', 'mlb');
INSERT INTO team_name_map VALUES ('Pittsburgh Pirates', 'Pittsburgh Pirates', 'mlb');
INSERT INTO team_name_map VALUES ('San Diego Padres', 'San Diego Padres', 'mlb');
INSERT INTO team_name_map VALUES ('San Francisco Giants', 'San Francisco Giants', 'mlb');
INSERT INTO team_name_map VALUES ('Seattle Mariners', 'Seattle Mariners', 'mlb');
INSERT INTO team_name_map VALUES ('St. Louis Cardinals', 'St. Louis Cardinals', 'mlb');
INSERT INTO team_name_map VALUES ('Tampa Bay Rays', 'Tampa Bay Rays', 'mlb');
INSERT INTO team_name_map VALUES ('Texas Rangers', 'Texas Rangers', 'mlb');
INSERT INTO team_name_map VALUES ('Toronto Blue Jays', 'Toronto Blue Jays', 'mlb');
INSERT INTO team_name_map VALUES ('Washington Nationals', 'Washington Nationals', 'mlb');
INSERT INTO team_name_map VALUES ('Anaheim Ducks', 'Anaheim Ducks', 'nhl');
INSERT INTO team_name_map VALUES ('Boston Bruins', 'Boston Bruins', 'nhl');
INSERT INTO team_name_map VALUES ('Buffalo Sabres', 'Buffalo Sabres', 'nhl');
INSERT INTO team_name_map VALUES ('Calgary Flames', 'Calgary Flames', 'nhl');
INSERT INTO team_name_map VALUES ('Carolina Hurricanes', 'Carolina Hurricanes', 'nhl');
INSERT INTO team_name_map VALUES ('Chicago Blackhawks', 'Chicago Blackhawks', 'nhl');
INSERT INTO team_name_map VALUES ('Colorado Avalanche', 'Colorado Avalanche', 'nhl');
INSERT INTO team_name_map VALUES ('Columbus Blue Jackets', 'Columbus Blue Jackets', 'nhl');
INSERT INTO team_name_map VALUES ('Dallas Stars', 'Dallas Stars', 'nhl');
INSERT INTO team_name_map VALUES ('Detroit Red Wings', 'Detroit Red Wings', 'nhl');
INSERT INTO team_name_map VALUES ('Edmonton Oilers', 'Edmonton Oilers', 'nhl');
INSERT INTO team_name_map VALUES ('Florida Panthers', 'Florida Panthers', 'nhl');
INSERT INTO team_name_map VALUES ('Los Angeles Kings', 'Los Angeles Kings', 'nhl');
INSERT INTO team_name_map VALUES ('Minnesota Wild', 'Minnesota Wild', 'nhl');
INSERT INTO team_name_map VALUES ('Nashville Predators', 'Nashville Predators', 'nhl');
INSERT INTO team_name_map VALUES ('New Jersey Devils', 'New Jersey Devils', 'nhl');
INSERT INTO team_name_map VALUES ('New York Islanders', 'New York Islanders', 'nhl');
INSERT INTO team_name_map VALUES ('New York Rangers', 'New York Rangers', 'nhl');
INSERT INTO team_name_map VALUES ('Ottawa Senators', 'Ottawa Senators', 'nhl');
INSERT INTO team_name_map VALUES ('Philadelphia Flyers', 'Philadelphia Flyers', 'nhl');
INSERT INTO team_name_map VALUES ('Pittsburgh Penguins', 'Pittsburgh Penguins', 'nhl');
INSERT INTO team_name_map VALUES ('San Jose Sharks', 'San Jose Sharks', 'nhl');
INSERT INTO team_name_map VALUES ('Seattle Kraken', 'Seattle Kraken', 'nhl');
INSERT INTO team_name_map VALUES ('St Louis Blues', 'St. Louis Blues', 'nhl');
INSERT INTO team_name_map VALUES ('Tampa Bay Lightning', 'Tampa Bay Lightning', 'nhl');
INSERT INTO team_name_map VALUES ('Toronto Maple Leafs', 'Toronto Maple Leafs', 'nhl');
INSERT INTO team_name_map VALUES ('Utah Hockey Club', 'Utah Mammoth', 'nhl');
INSERT INTO team_name_map VALUES ('Vancouver Canucks', 'Vancouver Canucks', 'nhl');
INSERT INTO team_name_map VALUES ('Vegas Golden Knights', 'Vegas Golden Knights', 'nhl');
INSERT INTO team_name_map VALUES ('Washington Capitals', 'Washington Capitals', 'nhl');
INSERT INTO team_name_map VALUES ('Winnipeg Jets', 'Winnipeg Jets', 'nhl');